feat: add build script for Windows and set OpenCV version in workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -3,6 +3,9 @@ name: Build OpenCV + OpenCV-Contrib
 on:
   push:
 
+env:
+  OPENCV_VERSION: 4.11.0
+
 jobs:
   build_packages:
     runs-on: windows-latest
@@ -18,12 +21,12 @@ jobs:
         with:
           submodules: recursive
 
-      #- name: Fetching submodule tags and checkout specific version
-      #  run: |
-      #    git submodule foreach --recursive 'git fetch --tags'
-      #    git submodule foreach --recursive '
-      #      git checkout tags/4.11.0 || echo "Tag 4.11.0 not found in $name";
-      #      git reset --hard tags/4.11.0 || echo "Reset failed for $name"'
+      - name: Fetching submodule tags and checkout specific version
+        run: |
+          git submodule foreach --recursive 'git fetch --tags'
+          git submodule foreach --recursive '
+            git checkout tags/4.11.0 || echo "Tag 4.11.0 not found in $name";
+            git reset --hard tags/4.11.0 || echo "Reset failed for $name"'
       
       - name: Add MSBuild
         uses: microsoft/setup-msbuild@v2
@@ -38,15 +41,15 @@ jobs:
           echo "VCPKG_ROOT=$(pwd)/vcpkg" | Out-File -FilePath $Env:GITHUB_ENV -Append
           echo "PATH=$Env:PATH;$(pwd)/vcpkg" | Out-File -FilePath $Env:GITHUB_ENV -Append
     
-    #  - name: Install Tesseract Dependency
-    #    run: |
-    #      & "$Env:VCPKG_ROOT\vcpkg" install tesseract:${{ matrix.arch }}-windows-static
-    #    shell: powershell
-      
-      - name: Install OpenCV-Contrib Dependencies
+      - name: Install Tesseract Dependency
         run: |
-          & "$Env:VCPKG_ROOT\vcpkg" install opencv4[contrib]:${{ matrix.arch }}-windows-static
+          & "$Env:VCPKG_ROOT\vcpkg" install tesseract:${{ matrix.arch }}-windows-static
         shell: powershell
+      
+    #  - name: Install OpenCV-Contrib Dependencies
+    #    run: |
+    #      & "$Env:VCPKG_ROOT\vcpkg" install opencv4[contrib]:${{ matrix.arch }}-windows-static
+    #    shell: powershell
       
       - name: Integrate VCPKG with CMake
         run: |
@@ -57,6 +60,19 @@ jobs:
         run: |
           & "$Env:VCPKG_ROOT\vcpkg" list
         shell: powershell
+      
+      - name: Build OpenCV
+      shell: powershell
+      run: |
+        Set-PSDebug -Trace 1
+        if ("${{matrix.platform}}" -eq 'win'){
+          . ".\build_windows.ps1"
+          BuildForWindows ${{matrix.arch}} "${env:VCPKG_ROOT}" $TRUE
+        }
+        elseif ("${{matrix.platform}}" -eq 'uwp'){
+          . ".\build_uwp.ps1"
+          BuildForUWP ${{matrix.arch}} "${env:VCPKG_ROOT}" $TRUE
+        }
         
 
 
